
FROM gradle:8.10-jdk21 AS build

WORKDIR /app


COPY . .

RUN ./gradlew clean bootJar -x test --no-daemon

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/build/libs/app.jar ./app.jar

EXPOSE 8080

ENV JAVA_TOOL_OPTIONS="-XX:+UseZGC"

CMD ["java", "-jar", "app.jar"]
