/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.pojos;


import com.medicod.database.enums.MedicodRemindersFrequency;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.LocalTime;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodReminders implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private ULong inventoryId;
    private LocalTime remindTime;
    private MedicodRemindersFrequency frequency;
    private Byte active;
    private LocalDateTime confirmedAt;
    private LocalDateTime lastSentAt;

    public MedicodReminders() {}

    public MedicodReminders(MedicodReminders value) {
        this.id = value.id;
        this.inventoryId = value.inventoryId;
        this.remindTime = value.remindTime;
        this.frequency = value.frequency;
        this.active = value.active;
        this.confirmedAt = value.confirmedAt;
        this.lastSentAt = value.lastSentAt;
    }

    public MedicodReminders(
        ULong id,
        ULong inventoryId,
        LocalTime remindTime,
        MedicodRemindersFrequency frequency,
        Byte active,
        LocalDateTime confirmedAt,
        LocalDateTime lastSentAt
    ) {
        this.id = id;
        this.inventoryId = inventoryId;
        this.remindTime = remindTime;
        this.frequency = frequency;
        this.active = active;
        this.confirmedAt = confirmedAt;
        this.lastSentAt = lastSentAt;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>medicod.medicod-reminders.id</code>.
     */
    public MedicodReminders setId(ULong id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.inventory_id</code>.
     */
    public ULong getInventoryId() {
        return this.inventoryId;
    }

    /**
     * Setter for <code>medicod.medicod-reminders.inventory_id</code>.
     */
    public MedicodReminders setInventoryId(ULong inventoryId) {
        this.inventoryId = inventoryId;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.remind_time</code>.
     */
    public LocalTime getRemindTime() {
        return this.remindTime;
    }

    /**
     * Setter for <code>medicod.medicod-reminders.remind_time</code>.
     */
    public MedicodReminders setRemindTime(LocalTime remindTime) {
        this.remindTime = remindTime;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.frequency</code>.
     */
    public MedicodRemindersFrequency getFrequency() {
        return this.frequency;
    }

    /**
     * Setter for <code>medicod.medicod-reminders.frequency</code>.
     */
    public MedicodReminders setFrequency(MedicodRemindersFrequency frequency) {
        this.frequency = frequency;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.active</code>.
     */
    public Byte getActive() {
        return this.active;
    }

    /**
     * Setter for <code>medicod.medicod-reminders.active</code>.
     */
    public MedicodReminders setActive(Byte active) {
        this.active = active;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.confirmed_at</code>.
     */
    public LocalDateTime getConfirmedAt() {
        return this.confirmedAt;
    }

    /**
     * Setter for <code>medicod.medicod-reminders.confirmed_at</code>.
     */
    public MedicodReminders setConfirmedAt(LocalDateTime confirmedAt) {
        this.confirmedAt = confirmedAt;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.last_sent_at</code>.
     */
    public LocalDateTime getLastSentAt() {
        return this.lastSentAt;
    }

    /**
     * Setter for <code>medicod.medicod-reminders.last_sent_at</code>.
     */
    public MedicodReminders setLastSentAt(LocalDateTime lastSentAt) {
        this.lastSentAt = lastSentAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MedicodReminders other = (MedicodReminders) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.inventoryId == null) {
            if (other.inventoryId != null)
                return false;
        }
        else if (!this.inventoryId.equals(other.inventoryId))
            return false;
        if (this.remindTime == null) {
            if (other.remindTime != null)
                return false;
        }
        else if (!this.remindTime.equals(other.remindTime))
            return false;
        if (this.frequency == null) {
            if (other.frequency != null)
                return false;
        }
        else if (!this.frequency.equals(other.frequency))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        if (this.confirmedAt == null) {
            if (other.confirmedAt != null)
                return false;
        }
        else if (!this.confirmedAt.equals(other.confirmedAt))
            return false;
        if (this.lastSentAt == null) {
            if (other.lastSentAt != null)
                return false;
        }
        else if (!this.lastSentAt.equals(other.lastSentAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.inventoryId == null) ? 0 : this.inventoryId.hashCode());
        result = prime * result + ((this.remindTime == null) ? 0 : this.remindTime.hashCode());
        result = prime * result + ((this.frequency == null) ? 0 : this.frequency.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.confirmedAt == null) ? 0 : this.confirmedAt.hashCode());
        result = prime * result + ((this.lastSentAt == null) ? 0 : this.lastSentAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MedicodReminders (");

        sb.append(id);
        sb.append(", ").append(inventoryId);
        sb.append(", ").append(remindTime);
        sb.append(", ").append(frequency);
        sb.append(", ").append(active);
        sb.append(", ").append(confirmedAt);
        sb.append(", ").append(lastSentAt);

        sb.append(")");
        return sb.toString();
    }
}
