/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodInventory implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private ULong userId;
    private ULong medicationId;
    private UInteger quantity;
    private String unit;
    private String lotCode;
    private LocalDate expires;

    public MedicodInventory() {}

    public MedicodInventory(MedicodInventory value) {
        this.id = value.id;
        this.userId = value.userId;
        this.medicationId = value.medicationId;
        this.quantity = value.quantity;
        this.unit = value.unit;
        this.lotCode = value.lotCode;
        this.expires = value.expires;
    }

    public MedicodInventory(
        ULong id,
        ULong userId,
        ULong medicationId,
        UInteger quantity,
        String unit,
        String lotCode,
        LocalDate expires
    ) {
        this.id = id;
        this.userId = userId;
        this.medicationId = medicationId;
        this.quantity = quantity;
        this.unit = unit;
        this.lotCode = lotCode;
        this.expires = expires;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>medicod.medicod-inventory.id</code>.
     */
    public MedicodInventory setId(ULong id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.user_id</code>.
     */
    public ULong getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>medicod.medicod-inventory.user_id</code>.
     */
    public MedicodInventory setUserId(ULong userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.medication_id</code>.
     */
    public ULong getMedicationId() {
        return this.medicationId;
    }

    /**
     * Setter for <code>medicod.medicod-inventory.medication_id</code>.
     */
    public MedicodInventory setMedicationId(ULong medicationId) {
        this.medicationId = medicationId;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.quantity</code>.
     */
    public UInteger getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>medicod.medicod-inventory.quantity</code>.
     */
    public MedicodInventory setQuantity(UInteger quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.unit</code>.
     */
    public String getUnit() {
        return this.unit;
    }

    /**
     * Setter for <code>medicod.medicod-inventory.unit</code>.
     */
    public MedicodInventory setUnit(String unit) {
        this.unit = unit;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.lot_code</code>.
     */
    public String getLotCode() {
        return this.lotCode;
    }

    /**
     * Setter for <code>medicod.medicod-inventory.lot_code</code>.
     */
    public MedicodInventory setLotCode(String lotCode) {
        this.lotCode = lotCode;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.expires</code>.
     */
    public LocalDate getExpires() {
        return this.expires;
    }

    /**
     * Setter for <code>medicod.medicod-inventory.expires</code>.
     */
    public MedicodInventory setExpires(LocalDate expires) {
        this.expires = expires;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MedicodInventory other = (MedicodInventory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.medicationId == null) {
            if (other.medicationId != null)
                return false;
        }
        else if (!this.medicationId.equals(other.medicationId))
            return false;
        if (this.quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!this.quantity.equals(other.quantity))
            return false;
        if (this.unit == null) {
            if (other.unit != null)
                return false;
        }
        else if (!this.unit.equals(other.unit))
            return false;
        if (this.lotCode == null) {
            if (other.lotCode != null)
                return false;
        }
        else if (!this.lotCode.equals(other.lotCode))
            return false;
        if (this.expires == null) {
            if (other.expires != null)
                return false;
        }
        else if (!this.expires.equals(other.expires))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.medicationId == null) ? 0 : this.medicationId.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.unit == null) ? 0 : this.unit.hashCode());
        result = prime * result + ((this.lotCode == null) ? 0 : this.lotCode.hashCode());
        result = prime * result + ((this.expires == null) ? 0 : this.expires.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MedicodInventory (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(medicationId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(unit);
        sb.append(", ").append(lotCode);
        sb.append(", ").append(expires);

        sb.append(")");
        return sb.toString();
    }
}
