/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.pojos;


import com.medicod.database.enums.MedicodUsersRole;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private String name;
    private String email;
    private String passwordHash;
    private MedicodUsersRole role;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public MedicodUsers() {}

    public MedicodUsers(MedicodUsers value) {
        this.id = value.id;
        this.name = value.name;
        this.email = value.email;
        this.passwordHash = value.passwordHash;
        this.role = value.role;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public MedicodUsers(
        ULong id,
        String name,
        String email,
        String passwordHash,
        MedicodUsersRole role,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.passwordHash = passwordHash;
        this.role = role;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>medicod.medicod-users.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>medicod.medicod-users.id</code>.
     */
    public MedicodUsers setId(ULong id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>medicod.medicod-users.name</code>.
     */
    public MedicodUsers setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>medicod.medicod-users.email</code>.
     */
    public MedicodUsers setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.password_hash</code>.
     */
    public String getPasswordHash() {
        return this.passwordHash;
    }

    /**
     * Setter for <code>medicod.medicod-users.password_hash</code>.
     */
    public MedicodUsers setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.role</code>.
     */
    public MedicodUsersRole getRole() {
        return this.role;
    }

    /**
     * Setter for <code>medicod.medicod-users.role</code>.
     */
    public MedicodUsers setRole(MedicodUsersRole role) {
        this.role = role;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>medicod.medicod-users.created_at</code>.
     */
    public MedicodUsers setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>medicod.medicod-users.updated_at</code>.
     */
    public MedicodUsers setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MedicodUsers other = (MedicodUsers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.passwordHash == null) {
            if (other.passwordHash != null)
                return false;
        }
        else if (!this.passwordHash.equals(other.passwordHash))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.passwordHash == null) ? 0 : this.passwordHash.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MedicodUsers (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(role);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
