/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodMedications implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong id;
    private String name;
    private String description;
    private LocalDate expirationDate;
    private LocalDateTime createdAt;

    public MedicodMedications() {}

    public MedicodMedications(MedicodMedications value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.expirationDate = value.expirationDate;
        this.createdAt = value.createdAt;
    }

    public MedicodMedications(
        ULong id,
        String name,
        String description,
        LocalDate expirationDate,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.expirationDate = expirationDate;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>medicod.medicod-medications.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>medicod.medicod-medications.id</code>.
     */
    public MedicodMedications setId(ULong id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-medications.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>medicod.medicod-medications.name</code>.
     */
    public MedicodMedications setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-medications.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>medicod.medicod-medications.description</code>.
     */
    public MedicodMedications setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-medications.expiration_date</code>.
     */
    public LocalDate getExpirationDate() {
        return this.expirationDate;
    }

    /**
     * Setter for <code>medicod.medicod-medications.expiration_date</code>.
     */
    public MedicodMedications setExpirationDate(LocalDate expirationDate) {
        this.expirationDate = expirationDate;
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-medications.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>medicod.medicod-medications.created_at</code>.
     */
    public MedicodMedications setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MedicodMedications other = (MedicodMedications) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.expirationDate == null) {
            if (other.expirationDate != null)
                return false;
        }
        else if (!this.expirationDate.equals(other.expirationDate))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.expirationDate == null) ? 0 : this.expirationDate.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MedicodMedications (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(expirationDate);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
