/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.daos;


import com.medicod.database.enums.MedicodRemindersFrequency;
import com.medicod.database.tables.MedicodReminders;
import com.medicod.database.tables.records.MedicodRemindersRecord;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodRemindersDao extends DAOImpl<MedicodRemindersRecord, com.medicod.database.tables.pojos.MedicodReminders, ULong> {

    /**
     * Create a new MedicodRemindersDao without any configuration
     */
    public MedicodRemindersDao() {
        super(MedicodReminders.MEDICOD_REMINDERS, com.medicod.database.tables.pojos.MedicodReminders.class);
    }

    /**
     * Create a new MedicodRemindersDao with an attached configuration
     */
    public MedicodRemindersDao(Configuration configuration) {
        super(MedicodReminders.MEDICOD_REMINDERS, com.medicod.database.tables.pojos.MedicodReminders.class, configuration);
    }

    @Override
    public ULong getId(com.medicod.database.tables.pojos.MedicodReminders object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(MedicodReminders.MEDICOD_REMINDERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchById(ULong... values) {
        return fetch(MedicodReminders.MEDICOD_REMINDERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.medicod.database.tables.pojos.MedicodReminders fetchOneById(ULong value) {
        return fetchOne(MedicodReminders.MEDICOD_REMINDERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.medicod.database.tables.pojos.MedicodReminders> fetchOptionalById(ULong value) {
        return fetchOptional(MedicodReminders.MEDICOD_REMINDERS.ID, value);
    }

    /**
     * Fetch records that have <code>inventory_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchRangeOfInventoryId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(MedicodReminders.MEDICOD_REMINDERS.INVENTORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>inventory_id IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchByInventoryId(ULong... values) {
        return fetch(MedicodReminders.MEDICOD_REMINDERS.INVENTORY_ID, values);
    }

    /**
     * Fetch records that have <code>remind_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchRangeOfRemindTime(LocalTime lowerInclusive, LocalTime upperInclusive) {
        return fetchRange(MedicodReminders.MEDICOD_REMINDERS.REMIND_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>remind_time IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchByRemindTime(LocalTime... values) {
        return fetch(MedicodReminders.MEDICOD_REMINDERS.REMIND_TIME, values);
    }

    /**
     * Fetch records that have <code>frequency BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchRangeOfFrequency(MedicodRemindersFrequency lowerInclusive, MedicodRemindersFrequency upperInclusive) {
        return fetchRange(MedicodReminders.MEDICOD_REMINDERS.FREQUENCY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>frequency IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchByFrequency(MedicodRemindersFrequency... values) {
        return fetch(MedicodReminders.MEDICOD_REMINDERS.FREQUENCY, values);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchRangeOfActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(MedicodReminders.MEDICOD_REMINDERS.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchByActive(Byte... values) {
        return fetch(MedicodReminders.MEDICOD_REMINDERS.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>confirmed_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchRangeOfConfirmedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MedicodReminders.MEDICOD_REMINDERS.CONFIRMED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>confirmed_at IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchByConfirmedAt(LocalDateTime... values) {
        return fetch(MedicodReminders.MEDICOD_REMINDERS.CONFIRMED_AT, values);
    }

    /**
     * Fetch records that have <code>last_sent_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchRangeOfLastSentAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MedicodReminders.MEDICOD_REMINDERS.LAST_SENT_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_sent_at IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodReminders> fetchByLastSentAt(LocalDateTime... values) {
        return fetch(MedicodReminders.MEDICOD_REMINDERS.LAST_SENT_AT, values);
    }
}
