/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.daos;


import com.medicod.database.enums.MedicodUsersRole;
import com.medicod.database.tables.MedicodUsers;
import com.medicod.database.tables.records.MedicodUsersRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodUsersDao extends DAOImpl<MedicodUsersRecord, com.medicod.database.tables.pojos.MedicodUsers, ULong> {

    /**
     * Create a new MedicodUsersDao without any configuration
     */
    public MedicodUsersDao() {
        super(MedicodUsers.MEDICOD_USERS, com.medicod.database.tables.pojos.MedicodUsers.class);
    }

    /**
     * Create a new MedicodUsersDao with an attached configuration
     */
    public MedicodUsersDao(Configuration configuration) {
        super(MedicodUsers.MEDICOD_USERS, com.medicod.database.tables.pojos.MedicodUsers.class, configuration);
    }

    @Override
    public ULong getId(com.medicod.database.tables.pojos.MedicodUsers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(MedicodUsers.MEDICOD_USERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchById(ULong... values) {
        return fetch(MedicodUsers.MEDICOD_USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.medicod.database.tables.pojos.MedicodUsers fetchOneById(ULong value) {
        return fetchOne(MedicodUsers.MEDICOD_USERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.medicod.database.tables.pojos.MedicodUsers> fetchOptionalById(ULong value) {
        return fetchOptional(MedicodUsers.MEDICOD_USERS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicodUsers.MEDICOD_USERS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchByName(String... values) {
        return fetch(MedicodUsers.MEDICOD_USERS.NAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicodUsers.MEDICOD_USERS.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchByEmail(String... values) {
        return fetch(MedicodUsers.MEDICOD_USERS.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public com.medicod.database.tables.pojos.MedicodUsers fetchOneByEmail(String value) {
        return fetchOne(MedicodUsers.MEDICOD_USERS.EMAIL, value);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public Optional<com.medicod.database.tables.pojos.MedicodUsers> fetchOptionalByEmail(String value) {
        return fetchOptional(MedicodUsers.MEDICOD_USERS.EMAIL, value);
    }

    /**
     * Fetch records that have <code>password_hash BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchRangeOfPasswordHash(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicodUsers.MEDICOD_USERS.PASSWORD_HASH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password_hash IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchByPasswordHash(String... values) {
        return fetch(MedicodUsers.MEDICOD_USERS.PASSWORD_HASH, values);
    }

    /**
     * Fetch records that have <code>role BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchRangeOfRole(MedicodUsersRole lowerInclusive, MedicodUsersRole upperInclusive) {
        return fetchRange(MedicodUsers.MEDICOD_USERS.ROLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchByRole(MedicodUsersRole... values) {
        return fetch(MedicodUsers.MEDICOD_USERS.ROLE, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MedicodUsers.MEDICOD_USERS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(MedicodUsers.MEDICOD_USERS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MedicodUsers.MEDICOD_USERS.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodUsers> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(MedicodUsers.MEDICOD_USERS.UPDATED_AT, values);
    }
}
