/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.daos;


import com.medicod.database.tables.MedicodMedications;
import com.medicod.database.tables.records.MedicodMedicationsRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodMedicationsDao extends DAOImpl<MedicodMedicationsRecord, com.medicod.database.tables.pojos.MedicodMedications, ULong> {

    /**
     * Create a new MedicodMedicationsDao without any configuration
     */
    public MedicodMedicationsDao() {
        super(MedicodMedications.MEDICOD_MEDICATIONS, com.medicod.database.tables.pojos.MedicodMedications.class);
    }

    /**
     * Create a new MedicodMedicationsDao with an attached configuration
     */
    public MedicodMedicationsDao(Configuration configuration) {
        super(MedicodMedications.MEDICOD_MEDICATIONS, com.medicod.database.tables.pojos.MedicodMedications.class, configuration);
    }

    @Override
    public ULong getId(com.medicod.database.tables.pojos.MedicodMedications object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(MedicodMedications.MEDICOD_MEDICATIONS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchById(ULong... values) {
        return fetch(MedicodMedications.MEDICOD_MEDICATIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.medicod.database.tables.pojos.MedicodMedications fetchOneById(ULong value) {
        return fetchOne(MedicodMedications.MEDICOD_MEDICATIONS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.medicod.database.tables.pojos.MedicodMedications> fetchOptionalById(ULong value) {
        return fetchOptional(MedicodMedications.MEDICOD_MEDICATIONS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicodMedications.MEDICOD_MEDICATIONS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchByName(String... values) {
        return fetch(MedicodMedications.MEDICOD_MEDICATIONS.NAME, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicodMedications.MEDICOD_MEDICATIONS.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchByDescription(String... values) {
        return fetch(MedicodMedications.MEDICOD_MEDICATIONS.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>expiration_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchRangeOfExpirationDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(MedicodMedications.MEDICOD_MEDICATIONS.EXPIRATION_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>expiration_date IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchByExpirationDate(LocalDate... values) {
        return fetch(MedicodMedications.MEDICOD_MEDICATIONS.EXPIRATION_DATE, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MedicodMedications.MEDICOD_MEDICATIONS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodMedications> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(MedicodMedications.MEDICOD_MEDICATIONS.CREATED_AT, values);
    }
}
