/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.daos;


import com.medicod.database.tables.MedicodInventory;
import com.medicod.database.tables.records.MedicodInventoryRecord;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodInventoryDao extends DAOImpl<MedicodInventoryRecord, com.medicod.database.tables.pojos.MedicodInventory, ULong> {

    /**
     * Create a new MedicodInventoryDao without any configuration
     */
    public MedicodInventoryDao() {
        super(MedicodInventory.MEDICOD_INVENTORY, com.medicod.database.tables.pojos.MedicodInventory.class);
    }

    /**
     * Create a new MedicodInventoryDao with an attached configuration
     */
    public MedicodInventoryDao(Configuration configuration) {
        super(MedicodInventory.MEDICOD_INVENTORY, com.medicod.database.tables.pojos.MedicodInventory.class, configuration);
    }

    @Override
    public ULong getId(com.medicod.database.tables.pojos.MedicodInventory object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(MedicodInventory.MEDICOD_INVENTORY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchById(ULong... values) {
        return fetch(MedicodInventory.MEDICOD_INVENTORY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.medicod.database.tables.pojos.MedicodInventory fetchOneById(ULong value) {
        return fetchOne(MedicodInventory.MEDICOD_INVENTORY.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.medicod.database.tables.pojos.MedicodInventory> fetchOptionalById(ULong value) {
        return fetchOptional(MedicodInventory.MEDICOD_INVENTORY.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchRangeOfUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(MedicodInventory.MEDICOD_INVENTORY.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchByUserId(ULong... values) {
        return fetch(MedicodInventory.MEDICOD_INVENTORY.USER_ID, values);
    }

    /**
     * Fetch records that have <code>medication_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchRangeOfMedicationId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(MedicodInventory.MEDICOD_INVENTORY.MEDICATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>medication_id IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchByMedicationId(ULong... values) {
        return fetch(MedicodInventory.MEDICOD_INVENTORY.MEDICATION_ID, values);
    }

    /**
     * Fetch records that have <code>quantity BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchRangeOfQuantity(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(MedicodInventory.MEDICOD_INVENTORY.QUANTITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>quantity IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchByQuantity(UInteger... values) {
        return fetch(MedicodInventory.MEDICOD_INVENTORY.QUANTITY, values);
    }

    /**
     * Fetch records that have <code>unit BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchRangeOfUnit(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicodInventory.MEDICOD_INVENTORY.UNIT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>unit IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchByUnit(String... values) {
        return fetch(MedicodInventory.MEDICOD_INVENTORY.UNIT, values);
    }

    /**
     * Fetch records that have <code>lot_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchRangeOfLotCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicodInventory.MEDICOD_INVENTORY.LOT_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lot_code IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchByLotCode(String... values) {
        return fetch(MedicodInventory.MEDICOD_INVENTORY.LOT_CODE, values);
    }

    /**
     * Fetch records that have <code>expires BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchRangeOfExpires(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(MedicodInventory.MEDICOD_INVENTORY.EXPIRES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>expires IN (values)</code>
     */
    public List<com.medicod.database.tables.pojos.MedicodInventory> fetchByExpires(LocalDate... values) {
        return fetch(MedicodInventory.MEDICOD_INVENTORY.EXPIRES, values);
    }
}
