/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables;


import com.medicod.database.Indexes;
import com.medicod.database.Keys;
import com.medicod.database.Medicod;
import com.medicod.database.tables.MedicodMedications.MedicodMedicationsPath;
import com.medicod.database.tables.MedicodReminders.MedicodRemindersPath;
import com.medicod.database.tables.MedicodUsers.MedicodUsersPath;
import com.medicod.database.tables.records.MedicodInventoryRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodInventory extends TableImpl<MedicodInventoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>medicod.medicod-inventory</code>
     */
    public static final MedicodInventory MEDICOD_INVENTORY = new MedicodInventory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedicodInventoryRecord> getRecordType() {
        return MedicodInventoryRecord.class;
    }

    /**
     * The column <code>medicod.medicod-inventory.id</code>.
     */
    public final TableField<MedicodInventoryRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>medicod.medicod-inventory.user_id</code>.
     */
    public final TableField<MedicodInventoryRecord, ULong> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>medicod.medicod-inventory.medication_id</code>.
     */
    public final TableField<MedicodInventoryRecord, ULong> MEDICATION_ID = createField(DSL.name("medication_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>medicod.medicod-inventory.quantity</code>.
     */
    public final TableField<MedicodInventoryRecord, UInteger> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>medicod.medicod-inventory.unit</code>.
     */
    public final TableField<MedicodInventoryRecord, String> UNIT = createField(DSL.name("unit"), SQLDataType.VARCHAR(16).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>medicod.medicod-inventory.lot_code</code>.
     */
    public final TableField<MedicodInventoryRecord, String> LOT_CODE = createField(DSL.name("lot_code"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>medicod.medicod-inventory.expires</code>.
     */
    public final TableField<MedicodInventoryRecord, LocalDate> EXPIRES = createField(DSL.name("expires"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "");

    private MedicodInventory(Name alias, Table<MedicodInventoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MedicodInventory(Name alias, Table<MedicodInventoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>medicod.medicod-inventory</code> table reference
     */
    public MedicodInventory(String alias) {
        this(DSL.name(alias), MEDICOD_INVENTORY);
    }

    /**
     * Create an aliased <code>medicod.medicod-inventory</code> table reference
     */
    public MedicodInventory(Name alias) {
        this(alias, MEDICOD_INVENTORY);
    }

    /**
     * Create a <code>medicod.medicod-inventory</code> table reference
     */
    public MedicodInventory() {
        this(DSL.name("medicod-inventory"), null);
    }

    public <O extends Record> MedicodInventory(Table<O> path, ForeignKey<O, MedicodInventoryRecord> childPath, InverseForeignKey<O, MedicodInventoryRecord> parentPath) {
        super(path, childPath, parentPath, MEDICOD_INVENTORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MedicodInventoryPath extends MedicodInventory implements Path<MedicodInventoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MedicodInventoryPath(Table<O> path, ForeignKey<O, MedicodInventoryRecord> childPath, InverseForeignKey<O, MedicodInventoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MedicodInventoryPath(Name alias, Table<MedicodInventoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MedicodInventoryPath as(String alias) {
            return new MedicodInventoryPath(DSL.name(alias), this);
        }

        @Override
        public MedicodInventoryPath as(Name alias) {
            return new MedicodInventoryPath(alias, this);
        }

        @Override
        public MedicodInventoryPath as(Table<?> alias) {
            return new MedicodInventoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Medicod.MEDICOD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MEDICOD_INVENTORY_IDX_INVENTORY_MEDICATION_ID, Indexes.MEDICOD_INVENTORY_IDX_INVENTORY_USER_ID);
    }

    @Override
    public Identity<MedicodInventoryRecord, ULong> getIdentity() {
        return (Identity<MedicodInventoryRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<MedicodInventoryRecord> getPrimaryKey() {
        return Keys.KEY_MEDICOD_INVENTORY_PRIMARY;
    }

    @Override
    public List<UniqueKey<MedicodInventoryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_MEDICOD_INVENTORY_UK_INVENTORY_USER_MED_LOT);
    }

    @Override
    public List<ForeignKey<MedicodInventoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_INVENTORY_MEDICATION_ID, Keys.FK_INVENTORY_USER_ID);
    }

    private transient MedicodMedicationsPath _medicodMedications;

    /**
     * Get the implicit join path to the
     * <code>medicod.medicod-medications</code> table.
     */
    public MedicodMedicationsPath medicodMedications() {
        if (_medicodMedications == null)
            _medicodMedications = new MedicodMedicationsPath(this, Keys.FK_INVENTORY_MEDICATION_ID, null);

        return _medicodMedications;
    }

    private transient MedicodUsersPath _medicodUsers;

    /**
     * Get the implicit join path to the <code>medicod.medicod-users</code>
     * table.
     */
    public MedicodUsersPath medicodUsers() {
        if (_medicodUsers == null)
            _medicodUsers = new MedicodUsersPath(this, Keys.FK_INVENTORY_USER_ID, null);

        return _medicodUsers;
    }

    private transient MedicodRemindersPath _medicodReminders;

    /**
     * Get the implicit to-many join path to the
     * <code>medicod.medicod-reminders</code> table
     */
    public MedicodRemindersPath medicodReminders() {
        if (_medicodReminders == null)
            _medicodReminders = new MedicodRemindersPath(this, null, Keys.FK_REMINDERS_INVENTORY_ID.getInverseKey());

        return _medicodReminders;
    }

    @Override
    public MedicodInventory as(String alias) {
        return new MedicodInventory(DSL.name(alias), this);
    }

    @Override
    public MedicodInventory as(Name alias) {
        return new MedicodInventory(alias, this);
    }

    @Override
    public MedicodInventory as(Table<?> alias) {
        return new MedicodInventory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodInventory rename(String name) {
        return new MedicodInventory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodInventory rename(Name name) {
        return new MedicodInventory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodInventory rename(Table<?> name) {
        return new MedicodInventory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodInventory where(Condition condition) {
        return new MedicodInventory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodInventory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodInventory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodInventory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodInventory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodInventory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodInventory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodInventory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodInventory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodInventory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
