/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables;


import com.medicod.database.Indexes;
import com.medicod.database.Keys;
import com.medicod.database.Medicod;
import com.medicod.database.enums.MedicodRemindersFrequency;
import com.medicod.database.tables.MedicodInventory.MedicodInventoryPath;
import com.medicod.database.tables.records.MedicodRemindersRecord;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodReminders extends TableImpl<MedicodRemindersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>medicod.medicod-reminders</code>
     */
    public static final MedicodReminders MEDICOD_REMINDERS = new MedicodReminders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedicodRemindersRecord> getRecordType() {
        return MedicodRemindersRecord.class;
    }

    /**
     * The column <code>medicod.medicod-reminders.id</code>.
     */
    public final TableField<MedicodRemindersRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>medicod.medicod-reminders.inventory_id</code>.
     */
    public final TableField<MedicodRemindersRecord, ULong> INVENTORY_ID = createField(DSL.name("inventory_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>medicod.medicod-reminders.remind_time</code>.
     */
    public final TableField<MedicodRemindersRecord, LocalTime> REMIND_TIME = createField(DSL.name("remind_time"), SQLDataType.LOCALTIME.nullable(false), this, "");

    /**
     * The column <code>medicod.medicod-reminders.frequency</code>.
     */
    public final TableField<MedicodRemindersRecord, MedicodRemindersFrequency> FREQUENCY = createField(DSL.name("frequency"), SQLDataType.VARCHAR(6).nullable(false).defaultValue(DSL.inline("'daily'", SQLDataType.VARCHAR)).asEnumDataType(MedicodRemindersFrequency.class), this, "");

    /**
     * The column <code>medicod.medicod-reminders.active</code>.
     */
    public final TableField<MedicodRemindersRecord, Byte> ACTIVE = createField(DSL.name("active"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>medicod.medicod-reminders.confirmed_at</code>.
     */
    public final TableField<MedicodRemindersRecord, LocalDateTime> CONFIRMED_AT = createField(DSL.name("confirmed_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>medicod.medicod-reminders.last_sent_at</code>.
     */
    public final TableField<MedicodRemindersRecord, LocalDateTime> LAST_SENT_AT = createField(DSL.name("last_sent_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    private MedicodReminders(Name alias, Table<MedicodRemindersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MedicodReminders(Name alias, Table<MedicodRemindersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>medicod.medicod-reminders</code> table reference
     */
    public MedicodReminders(String alias) {
        this(DSL.name(alias), MEDICOD_REMINDERS);
    }

    /**
     * Create an aliased <code>medicod.medicod-reminders</code> table reference
     */
    public MedicodReminders(Name alias) {
        this(alias, MEDICOD_REMINDERS);
    }

    /**
     * Create a <code>medicod.medicod-reminders</code> table reference
     */
    public MedicodReminders() {
        this(DSL.name("medicod-reminders"), null);
    }

    public <O extends Record> MedicodReminders(Table<O> path, ForeignKey<O, MedicodRemindersRecord> childPath, InverseForeignKey<O, MedicodRemindersRecord> parentPath) {
        super(path, childPath, parentPath, MEDICOD_REMINDERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MedicodRemindersPath extends MedicodReminders implements Path<MedicodRemindersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MedicodRemindersPath(Table<O> path, ForeignKey<O, MedicodRemindersRecord> childPath, InverseForeignKey<O, MedicodRemindersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MedicodRemindersPath(Name alias, Table<MedicodRemindersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MedicodRemindersPath as(String alias) {
            return new MedicodRemindersPath(DSL.name(alias), this);
        }

        @Override
        public MedicodRemindersPath as(Name alias) {
            return new MedicodRemindersPath(alias, this);
        }

        @Override
        public MedicodRemindersPath as(Table<?> alias) {
            return new MedicodRemindersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Medicod.MEDICOD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MEDICOD_REMINDERS_IDX_REMINDERS_INVENTORY_ID);
    }

    @Override
    public Identity<MedicodRemindersRecord, ULong> getIdentity() {
        return (Identity<MedicodRemindersRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<MedicodRemindersRecord> getPrimaryKey() {
        return Keys.KEY_MEDICOD_REMINDERS_PRIMARY;
    }

    @Override
    public List<ForeignKey<MedicodRemindersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_REMINDERS_INVENTORY_ID);
    }

    private transient MedicodInventoryPath _medicodInventory;

    /**
     * Get the implicit join path to the <code>medicod.medicod-inventory</code>
     * table.
     */
    public MedicodInventoryPath medicodInventory() {
        if (_medicodInventory == null)
            _medicodInventory = new MedicodInventoryPath(this, Keys.FK_REMINDERS_INVENTORY_ID, null);

        return _medicodInventory;
    }

    @Override
    public MedicodReminders as(String alias) {
        return new MedicodReminders(DSL.name(alias), this);
    }

    @Override
    public MedicodReminders as(Name alias) {
        return new MedicodReminders(alias, this);
    }

    @Override
    public MedicodReminders as(Table<?> alias) {
        return new MedicodReminders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodReminders rename(String name) {
        return new MedicodReminders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodReminders rename(Name name) {
        return new MedicodReminders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodReminders rename(Table<?> name) {
        return new MedicodReminders(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodReminders where(Condition condition) {
        return new MedicodReminders(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodReminders where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodReminders where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodReminders where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodReminders where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodReminders where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodReminders where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodReminders where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodReminders whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodReminders whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
