/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables;


import com.medicod.database.Keys;
import com.medicod.database.Medicod;
import com.medicod.database.enums.MedicodUsersRole;
import com.medicod.database.tables.MedicodInventory.MedicodInventoryPath;
import com.medicod.database.tables.records.MedicodUsersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodUsers extends TableImpl<MedicodUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>medicod.medicod-users</code>
     */
    public static final MedicodUsers MEDICOD_USERS = new MedicodUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedicodUsersRecord> getRecordType() {
        return MedicodUsersRecord.class;
    }

    /**
     * The column <code>medicod.medicod-users.id</code>.
     */
    public final TableField<MedicodUsersRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>medicod.medicod-users.name</code>.
     */
    public final TableField<MedicodUsersRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(120).nullable(false), this, "");

    /**
     * The column <code>medicod.medicod-users.email</code>.
     */
    public final TableField<MedicodUsersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>medicod.medicod-users.password_hash</code>.
     */
    public final TableField<MedicodUsersRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>medicod.medicod-users.role</code>.
     */
    public final TableField<MedicodUsersRecord, MedicodUsersRole> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(5).nullable(false).defaultValue(DSL.inline("'USER'", SQLDataType.VARCHAR)).asEnumDataType(MedicodUsersRole.class), this, "");

    /**
     * The column <code>medicod.medicod-users.created_at</code>.
     */
    public final TableField<MedicodUsersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>medicod.medicod-users.updated_at</code>.
     */
    public final TableField<MedicodUsersRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    private MedicodUsers(Name alias, Table<MedicodUsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MedicodUsers(Name alias, Table<MedicodUsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>medicod.medicod-users</code> table reference
     */
    public MedicodUsers(String alias) {
        this(DSL.name(alias), MEDICOD_USERS);
    }

    /**
     * Create an aliased <code>medicod.medicod-users</code> table reference
     */
    public MedicodUsers(Name alias) {
        this(alias, MEDICOD_USERS);
    }

    /**
     * Create a <code>medicod.medicod-users</code> table reference
     */
    public MedicodUsers() {
        this(DSL.name("medicod-users"), null);
    }

    public <O extends Record> MedicodUsers(Table<O> path, ForeignKey<O, MedicodUsersRecord> childPath, InverseForeignKey<O, MedicodUsersRecord> parentPath) {
        super(path, childPath, parentPath, MEDICOD_USERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MedicodUsersPath extends MedicodUsers implements Path<MedicodUsersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MedicodUsersPath(Table<O> path, ForeignKey<O, MedicodUsersRecord> childPath, InverseForeignKey<O, MedicodUsersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MedicodUsersPath(Name alias, Table<MedicodUsersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MedicodUsersPath as(String alias) {
            return new MedicodUsersPath(DSL.name(alias), this);
        }

        @Override
        public MedicodUsersPath as(Name alias) {
            return new MedicodUsersPath(alias, this);
        }

        @Override
        public MedicodUsersPath as(Table<?> alias) {
            return new MedicodUsersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Medicod.MEDICOD;
    }

    @Override
    public Identity<MedicodUsersRecord, ULong> getIdentity() {
        return (Identity<MedicodUsersRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<MedicodUsersRecord> getPrimaryKey() {
        return Keys.KEY_MEDICOD_USERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<MedicodUsersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_MEDICOD_USERS_UK_USERS_EMAIL);
    }

    private transient MedicodInventoryPath _medicodInventory;

    /**
     * Get the implicit to-many join path to the
     * <code>medicod.medicod-inventory</code> table
     */
    public MedicodInventoryPath medicodInventory() {
        if (_medicodInventory == null)
            _medicodInventory = new MedicodInventoryPath(this, null, Keys.FK_INVENTORY_USER_ID.getInverseKey());

        return _medicodInventory;
    }

    @Override
    public MedicodUsers as(String alias) {
        return new MedicodUsers(DSL.name(alias), this);
    }

    @Override
    public MedicodUsers as(Name alias) {
        return new MedicodUsers(alias, this);
    }

    @Override
    public MedicodUsers as(Table<?> alias) {
        return new MedicodUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodUsers rename(String name) {
        return new MedicodUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodUsers rename(Name name) {
        return new MedicodUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodUsers rename(Table<?> name) {
        return new MedicodUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodUsers where(Condition condition) {
        return new MedicodUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
