/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables;


import com.medicod.database.Keys;
import com.medicod.database.Medicod;
import com.medicod.database.tables.MedicodInventory.MedicodInventoryPath;
import com.medicod.database.tables.records.MedicodMedicationsRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodMedications extends TableImpl<MedicodMedicationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>medicod.medicod-medications</code>
     */
    public static final MedicodMedications MEDICOD_MEDICATIONS = new MedicodMedications();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedicodMedicationsRecord> getRecordType() {
        return MedicodMedicationsRecord.class;
    }

    /**
     * The column <code>medicod.medicod-medications.id</code>.
     */
    public final TableField<MedicodMedicationsRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>medicod.medicod-medications.name</code>.
     */
    public final TableField<MedicodMedicationsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(120).nullable(false), this, "");

    /**
     * The column <code>medicod.medicod-medications.description</code>.
     */
    public final TableField<MedicodMedicationsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column <code>medicod.medicod-medications.expiration_date</code>.
     */
    public final TableField<MedicodMedicationsRecord, LocalDate> EXPIRATION_DATE = createField(DSL.name("expiration_date"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>medicod.medicod-medications.created_at</code>.
     */
    public final TableField<MedicodMedicationsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private MedicodMedications(Name alias, Table<MedicodMedicationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MedicodMedications(Name alias, Table<MedicodMedicationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>medicod.medicod-medications</code> table
     * reference
     */
    public MedicodMedications(String alias) {
        this(DSL.name(alias), MEDICOD_MEDICATIONS);
    }

    /**
     * Create an aliased <code>medicod.medicod-medications</code> table
     * reference
     */
    public MedicodMedications(Name alias) {
        this(alias, MEDICOD_MEDICATIONS);
    }

    /**
     * Create a <code>medicod.medicod-medications</code> table reference
     */
    public MedicodMedications() {
        this(DSL.name("medicod-medications"), null);
    }

    public <O extends Record> MedicodMedications(Table<O> path, ForeignKey<O, MedicodMedicationsRecord> childPath, InverseForeignKey<O, MedicodMedicationsRecord> parentPath) {
        super(path, childPath, parentPath, MEDICOD_MEDICATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MedicodMedicationsPath extends MedicodMedications implements Path<MedicodMedicationsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MedicodMedicationsPath(Table<O> path, ForeignKey<O, MedicodMedicationsRecord> childPath, InverseForeignKey<O, MedicodMedicationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MedicodMedicationsPath(Name alias, Table<MedicodMedicationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MedicodMedicationsPath as(String alias) {
            return new MedicodMedicationsPath(DSL.name(alias), this);
        }

        @Override
        public MedicodMedicationsPath as(Name alias) {
            return new MedicodMedicationsPath(alias, this);
        }

        @Override
        public MedicodMedicationsPath as(Table<?> alias) {
            return new MedicodMedicationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Medicod.MEDICOD;
    }

    @Override
    public Identity<MedicodMedicationsRecord, ULong> getIdentity() {
        return (Identity<MedicodMedicationsRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<MedicodMedicationsRecord> getPrimaryKey() {
        return Keys.KEY_MEDICOD_MEDICATIONS_PRIMARY;
    }

    private transient MedicodInventoryPath _medicodInventory;

    /**
     * Get the implicit to-many join path to the
     * <code>medicod.medicod-inventory</code> table
     */
    public MedicodInventoryPath medicodInventory() {
        if (_medicodInventory == null)
            _medicodInventory = new MedicodInventoryPath(this, null, Keys.FK_INVENTORY_MEDICATION_ID.getInverseKey());

        return _medicodInventory;
    }

    @Override
    public MedicodMedications as(String alias) {
        return new MedicodMedications(DSL.name(alias), this);
    }

    @Override
    public MedicodMedications as(Name alias) {
        return new MedicodMedications(alias, this);
    }

    @Override
    public MedicodMedications as(Table<?> alias) {
        return new MedicodMedications(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodMedications rename(String name) {
        return new MedicodMedications(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodMedications rename(Name name) {
        return new MedicodMedications(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicodMedications rename(Table<?> name) {
        return new MedicodMedications(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodMedications where(Condition condition) {
        return new MedicodMedications(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodMedications where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodMedications where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodMedications where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodMedications where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodMedications where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodMedications where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedicodMedications where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodMedications whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedicodMedications whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
