/*
 * This file is generated by jOOQ.
 */
package com.medicod.database;


import com.medicod.database.tables.MedicodInventory;
import com.medicod.database.tables.MedicodReminders;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in medicod.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MEDICOD_INVENTORY_IDX_INVENTORY_MEDICATION_ID = Internal.createIndex(DSL.name("idx_inventory_medication_id"), MedicodInventory.MEDICOD_INVENTORY, new OrderField[] { MedicodInventory.MEDICOD_INVENTORY.MEDICATION_ID }, false);
    public static final Index MEDICOD_INVENTORY_IDX_INVENTORY_USER_ID = Internal.createIndex(DSL.name("idx_inventory_user_id"), MedicodInventory.MEDICOD_INVENTORY, new OrderField[] { MedicodInventory.MEDICOD_INVENTORY.USER_ID }, false);
    public static final Index MEDICOD_REMINDERS_IDX_REMINDERS_INVENTORY_ID = Internal.createIndex(DSL.name("idx_reminders_inventory_id"), MedicodReminders.MEDICOD_REMINDERS, new OrderField[] { MedicodReminders.MEDICOD_REMINDERS.INVENTORY_ID }, false);
}
