/*
 * This file is generated by jOOQ.
 */
package com.medicod.database;


import com.medicod.database.tables.MedicodInventory;
import com.medicod.database.tables.MedicodMedications;
import com.medicod.database.tables.MedicodReminders;
import com.medicod.database.tables.MedicodUsers;
import com.medicod.database.tables.records.MedicodInventoryRecord;
import com.medicod.database.tables.records.MedicodMedicationsRecord;
import com.medicod.database.tables.records.MedicodRemindersRecord;
import com.medicod.database.tables.records.MedicodUsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * medicod.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MedicodInventoryRecord> KEY_MEDICOD_INVENTORY_PRIMARY = Internal.createUniqueKey(MedicodInventory.MEDICOD_INVENTORY, DSL.name("KEY_medicod-inventory_PRIMARY"), new TableField[] { MedicodInventory.MEDICOD_INVENTORY.ID }, true);
    public static final UniqueKey<MedicodInventoryRecord> KEY_MEDICOD_INVENTORY_UK_INVENTORY_USER_MED_LOT = Internal.createUniqueKey(MedicodInventory.MEDICOD_INVENTORY, DSL.name("KEY_medicod-inventory_uk_inventory_user_med_lot"), new TableField[] { MedicodInventory.MEDICOD_INVENTORY.USER_ID, MedicodInventory.MEDICOD_INVENTORY.MEDICATION_ID, MedicodInventory.MEDICOD_INVENTORY.LOT_CODE }, true);
    public static final UniqueKey<MedicodMedicationsRecord> KEY_MEDICOD_MEDICATIONS_PRIMARY = Internal.createUniqueKey(MedicodMedications.MEDICOD_MEDICATIONS, DSL.name("KEY_medicod-medications_PRIMARY"), new TableField[] { MedicodMedications.MEDICOD_MEDICATIONS.ID }, true);
    public static final UniqueKey<MedicodRemindersRecord> KEY_MEDICOD_REMINDERS_PRIMARY = Internal.createUniqueKey(MedicodReminders.MEDICOD_REMINDERS, DSL.name("KEY_medicod-reminders_PRIMARY"), new TableField[] { MedicodReminders.MEDICOD_REMINDERS.ID }, true);
    public static final UniqueKey<MedicodUsersRecord> KEY_MEDICOD_USERS_PRIMARY = Internal.createUniqueKey(MedicodUsers.MEDICOD_USERS, DSL.name("KEY_medicod-users_PRIMARY"), new TableField[] { MedicodUsers.MEDICOD_USERS.ID }, true);
    public static final UniqueKey<MedicodUsersRecord> KEY_MEDICOD_USERS_UK_USERS_EMAIL = Internal.createUniqueKey(MedicodUsers.MEDICOD_USERS, DSL.name("KEY_medicod-users_uk_users_email"), new TableField[] { MedicodUsers.MEDICOD_USERS.EMAIL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MedicodInventoryRecord, MedicodMedicationsRecord> FK_INVENTORY_MEDICATION_ID = Internal.createForeignKey(MedicodInventory.MEDICOD_INVENTORY, DSL.name("fk_inventory_medication_id"), new TableField[] { MedicodInventory.MEDICOD_INVENTORY.MEDICATION_ID }, Keys.KEY_MEDICOD_MEDICATIONS_PRIMARY, new TableField[] { MedicodMedications.MEDICOD_MEDICATIONS.ID }, true);
    public static final ForeignKey<MedicodInventoryRecord, MedicodUsersRecord> FK_INVENTORY_USER_ID = Internal.createForeignKey(MedicodInventory.MEDICOD_INVENTORY, DSL.name("fk_inventory_user_id"), new TableField[] { MedicodInventory.MEDICOD_INVENTORY.USER_ID }, Keys.KEY_MEDICOD_USERS_PRIMARY, new TableField[] { MedicodUsers.MEDICOD_USERS.ID }, true);
    public static final ForeignKey<MedicodRemindersRecord, MedicodInventoryRecord> FK_REMINDERS_INVENTORY_ID = Internal.createForeignKey(MedicodReminders.MEDICOD_REMINDERS, DSL.name("fk_reminders_inventory_id"), new TableField[] { MedicodReminders.MEDICOD_REMINDERS.INVENTORY_ID }, Keys.KEY_MEDICOD_INVENTORY_PRIMARY, new TableField[] { MedicodInventory.MEDICOD_INVENTORY.ID }, true);
}
