/*
 * This file is generated by jOOQ.
 */
package com.medicod.database;


import com.medicod.database.tables.MedicodInventory;
import com.medicod.database.tables.MedicodMedications;
import com.medicod.database.tables.MedicodReminders;
import com.medicod.database.tables.MedicodUsers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Medicod extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>medicod</code>
     */
    public static final Medicod MEDICOD = new Medicod();

    /**
     * The table <code>medicod.medicod-inventory</code>.
     */
    public final MedicodInventory MEDICOD_INVENTORY = MedicodInventory.MEDICOD_INVENTORY;

    /**
     * The table <code>medicod.medicod-medications</code>.
     */
    public final MedicodMedications MEDICOD_MEDICATIONS = MedicodMedications.MEDICOD_MEDICATIONS;

    /**
     * The table <code>medicod.medicod-reminders</code>.
     */
    public final MedicodReminders MEDICOD_REMINDERS = MedicodReminders.MEDICOD_REMINDERS;

    /**
     * The table <code>medicod.medicod-users</code>.
     */
    public final MedicodUsers MEDICOD_USERS = MedicodUsers.MEDICOD_USERS;

    /**
     * No further instances allowed
     */
    private Medicod() {
        super("medicod", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            MedicodInventory.MEDICOD_INVENTORY,
            MedicodMedications.MEDICOD_MEDICATIONS,
            MedicodReminders.MEDICOD_REMINDERS,
            MedicodUsers.MEDICOD_USERS
        );
    }
}
