/*
 * This file is generated by jOOQ.
 */
package com.medicod.database;


import com.medicod.database.tables.MedicodInventory;
import com.medicod.database.tables.MedicodMedications;
import com.medicod.database.tables.MedicodReminders;
import com.medicod.database.tables.MedicodUsers;


/**
 * Convenience access to all tables in medicod.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>medicod.medicod-inventory</code>.
     */
    public static final MedicodInventory MEDICOD_INVENTORY = MedicodInventory.MEDICOD_INVENTORY;

    /**
     * The table <code>medicod.medicod-medications</code>.
     */
    public static final MedicodMedications MEDICOD_MEDICATIONS = MedicodMedications.MEDICOD_MEDICATIONS;

    /**
     * The table <code>medicod.medicod-reminders</code>.
     */
    public static final MedicodReminders MEDICOD_REMINDERS = MedicodReminders.MEDICOD_REMINDERS;

    /**
     * The table <code>medicod.medicod-users</code>.
     */
    public static final MedicodUsers MEDICOD_USERS = MedicodUsers.MEDICOD_USERS;
}
