/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.records;


import com.medicod.database.tables.MedicodMedications;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodMedicationsRecord extends UpdatableRecordImpl<MedicodMedicationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>medicod.medicod-medications.id</code>.
     */
    public MedicodMedicationsRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-medications.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>medicod.medicod-medications.name</code>.
     */
    public MedicodMedicationsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-medications.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>medicod.medicod-medications.description</code>.
     */
    public MedicodMedicationsRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-medications.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>medicod.medicod-medications.expiration_date</code>.
     */
    public MedicodMedicationsRecord setExpirationDate(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-medications.expiration_date</code>.
     */
    public LocalDate getExpirationDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>medicod.medicod-medications.created_at</code>.
     */
    public MedicodMedicationsRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-medications.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicodMedicationsRecord
     */
    public MedicodMedicationsRecord() {
        super(MedicodMedications.MEDICOD_MEDICATIONS);
    }

    /**
     * Create a detached, initialised MedicodMedicationsRecord
     */
    public MedicodMedicationsRecord(ULong id, String name, String description, LocalDate expirationDate, LocalDateTime createdAt) {
        super(MedicodMedications.MEDICOD_MEDICATIONS);

        setId(id);
        setName(name);
        setDescription(description);
        setExpirationDate(expirationDate);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MedicodMedicationsRecord
     */
    public MedicodMedicationsRecord(com.medicod.database.tables.pojos.MedicodMedications value) {
        super(MedicodMedications.MEDICOD_MEDICATIONS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setExpirationDate(value.getExpirationDate());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
