/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.records;


import com.medicod.database.enums.MedicodUsersRole;
import com.medicod.database.tables.MedicodUsers;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodUsersRecord extends UpdatableRecordImpl<MedicodUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>medicod.medicod-users.id</code>.
     */
    public MedicodUsersRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>medicod.medicod-users.name</code>.
     */
    public MedicodUsersRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>medicod.medicod-users.email</code>.
     */
    public MedicodUsersRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>medicod.medicod-users.password_hash</code>.
     */
    public MedicodUsersRecord setPasswordHash(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>medicod.medicod-users.role</code>.
     */
    public MedicodUsersRecord setRole(MedicodUsersRole value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.role</code>.
     */
    public MedicodUsersRole getRole() {
        return (MedicodUsersRole) get(4);
    }

    /**
     * Setter for <code>medicod.medicod-users.created_at</code>.
     */
    public MedicodUsersRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>medicod.medicod-users.updated_at</code>.
     */
    public MedicodUsersRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-users.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicodUsersRecord
     */
    public MedicodUsersRecord() {
        super(MedicodUsers.MEDICOD_USERS);
    }

    /**
     * Create a detached, initialised MedicodUsersRecord
     */
    public MedicodUsersRecord(ULong id, String name, String email, String passwordHash, MedicodUsersRole role, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(MedicodUsers.MEDICOD_USERS);

        setId(id);
        setName(name);
        setEmail(email);
        setPasswordHash(passwordHash);
        setRole(role);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MedicodUsersRecord
     */
    public MedicodUsersRecord(com.medicod.database.tables.pojos.MedicodUsers value) {
        super(MedicodUsers.MEDICOD_USERS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmail(value.getEmail());
            setPasswordHash(value.getPasswordHash());
            setRole(value.getRole());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
