/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.records;


import com.medicod.database.enums.MedicodRemindersFrequency;
import com.medicod.database.tables.MedicodReminders;

import java.time.LocalDateTime;
import java.time.LocalTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodRemindersRecord extends UpdatableRecordImpl<MedicodRemindersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>medicod.medicod-reminders.id</code>.
     */
    public MedicodRemindersRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>medicod.medicod-reminders.inventory_id</code>.
     */
    public MedicodRemindersRecord setInventoryId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.inventory_id</code>.
     */
    public ULong getInventoryId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>medicod.medicod-reminders.remind_time</code>.
     */
    public MedicodRemindersRecord setRemindTime(LocalTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.remind_time</code>.
     */
    public LocalTime getRemindTime() {
        return (LocalTime) get(2);
    }

    /**
     * Setter for <code>medicod.medicod-reminders.frequency</code>.
     */
    public MedicodRemindersRecord setFrequency(MedicodRemindersFrequency value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.frequency</code>.
     */
    public MedicodRemindersFrequency getFrequency() {
        return (MedicodRemindersFrequency) get(3);
    }

    /**
     * Setter for <code>medicod.medicod-reminders.active</code>.
     */
    public MedicodRemindersRecord setActive(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.active</code>.
     */
    public Byte getActive() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>medicod.medicod-reminders.confirmed_at</code>.
     */
    public MedicodRemindersRecord setConfirmedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.confirmed_at</code>.
     */
    public LocalDateTime getConfirmedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>medicod.medicod-reminders.last_sent_at</code>.
     */
    public MedicodRemindersRecord setLastSentAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-reminders.last_sent_at</code>.
     */
    public LocalDateTime getLastSentAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicodRemindersRecord
     */
    public MedicodRemindersRecord() {
        super(MedicodReminders.MEDICOD_REMINDERS);
    }

    /**
     * Create a detached, initialised MedicodRemindersRecord
     */
    public MedicodRemindersRecord(ULong id, ULong inventoryId, LocalTime remindTime, MedicodRemindersFrequency frequency, Byte active, LocalDateTime confirmedAt, LocalDateTime lastSentAt) {
        super(MedicodReminders.MEDICOD_REMINDERS);

        setId(id);
        setInventoryId(inventoryId);
        setRemindTime(remindTime);
        setFrequency(frequency);
        setActive(active);
        setConfirmedAt(confirmedAt);
        setLastSentAt(lastSentAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MedicodRemindersRecord
     */
    public MedicodRemindersRecord(com.medicod.database.tables.pojos.MedicodReminders value) {
        super(MedicodReminders.MEDICOD_REMINDERS);

        if (value != null) {
            setId(value.getId());
            setInventoryId(value.getInventoryId());
            setRemindTime(value.getRemindTime());
            setFrequency(value.getFrequency());
            setActive(value.getActive());
            setConfirmedAt(value.getConfirmedAt());
            setLastSentAt(value.getLastSentAt());
            resetChangedOnNotNull();
        }
    }
}
