/*
 * This file is generated by jOOQ.
 */
package com.medicod.database.tables.records;


import com.medicod.database.tables.MedicodInventory;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedicodInventoryRecord extends UpdatableRecordImpl<MedicodInventoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>medicod.medicod-inventory.id</code>.
     */
    public MedicodInventoryRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>medicod.medicod-inventory.user_id</code>.
     */
    public MedicodInventoryRecord setUserId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>medicod.medicod-inventory.medication_id</code>.
     */
    public MedicodInventoryRecord setMedicationId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.medication_id</code>.
     */
    public ULong getMedicationId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>medicod.medicod-inventory.quantity</code>.
     */
    public MedicodInventoryRecord setQuantity(UInteger value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.quantity</code>.
     */
    public UInteger getQuantity() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>medicod.medicod-inventory.unit</code>.
     */
    public MedicodInventoryRecord setUnit(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.unit</code>.
     */
    public String getUnit() {
        return (String) get(4);
    }

    /**
     * Setter for <code>medicod.medicod-inventory.lot_code</code>.
     */
    public MedicodInventoryRecord setLotCode(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.lot_code</code>.
     */
    public String getLotCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>medicod.medicod-inventory.expires</code>.
     */
    public MedicodInventoryRecord setExpires(LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>medicod.medicod-inventory.expires</code>.
     */
    public LocalDate getExpires() {
        return (LocalDate) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicodInventoryRecord
     */
    public MedicodInventoryRecord() {
        super(MedicodInventory.MEDICOD_INVENTORY);
    }

    /**
     * Create a detached, initialised MedicodInventoryRecord
     */
    public MedicodInventoryRecord(ULong id, ULong userId, ULong medicationId, UInteger quantity, String unit, String lotCode, LocalDate expires) {
        super(MedicodInventory.MEDICOD_INVENTORY);

        setId(id);
        setUserId(userId);
        setMedicationId(medicationId);
        setQuantity(quantity);
        setUnit(unit);
        setLotCode(lotCode);
        setExpires(expires);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MedicodInventoryRecord
     */
    public MedicodInventoryRecord(com.medicod.database.tables.pojos.MedicodInventory value) {
        super(MedicodInventory.MEDICOD_INVENTORY);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setMedicationId(value.getMedicationId());
            setQuantity(value.getQuantity());
            setUnit(value.getUnit());
            setLotCode(value.getLotCode());
            setExpires(value.getExpires());
            resetChangedOnNotNull();
        }
    }
}
